name: 'Upload a Build Artifact'
description: 'Upload a build artifact that can be used by subsequent workflow steps'
author: 'GitHub'
inputs:
 
  # A directory will be created with this name and populated with the items in the path below.
  # Then it will be compressed into a zip file.
  name:
    description: 'Artifact name'
    required: true
  
  path:
    description: 'Directory containing files to upload'
    required: true

runs:
  # Plugins live on the runner and are only available to a certain set of first party actions.
  plugin: 'publish'
