name: 'Upload a Build Artifact'
description: 'Upload a build artifact that can be used by subsequent workflow steps'
author: 'GitHub'
inputs: 
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'